source 'http://rubygems.org'

gem 'rails', '3.1.0.rc8'

gem 'mongo', '>= 1.0.7'
gem 'mongoid', '2.2.0'
gem 'mongoid_taggable'
gem 'bson_ext'

gem 'css3buttons'
gem 'omniauth'

# Asset template engines
gem 'sass-rails', "~> 3.1.0.rc"
gem 'coffee-script'
gem 'uglifier'

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
