source 'http://rubygems.org'

gem 'rails', '3.0.9'


gem 'sqlite3'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

 group :development, :test do
   gem 'rspec'
   gem 'rspec-rails'
   gem 'autotest'
 end
